# Generated by Django 5.0.7 on 2024-07-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0002_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('telephony', 'Telephony'), ('internet', 'Internet')], default='TELEPHONY', max_length=20),
        ),
    ]
